// This file is auto-generated by @hey-api/openapi-ts

import { createClient, createConfig, type Options } from '@hey-api/client-fetch';
import type { RootApiHelloGetError, RootApiHelloGetResponse, DepotApiDepotNameGetData, DepotApiDepotNameGetError, DepotApiDepotNameGetResponse, DepotsApiDepotsGetError, DepotsApiDepotsGetResponse } from './types.gen';

export const client = createClient(createConfig());

/**
 * Root
 */
export const rootApiHelloGet = <ThrowOnError extends boolean = false>(options?: Options<unknown, ThrowOnError>) => { return (options?.client ?? client).get<RootApiHelloGetResponse, RootApiHelloGetError, ThrowOnError>({
    ...options,
    url: '/api/hello'
}); };

/**
 * Depot
 */
export const depotApiDepotNameGet = <ThrowOnError extends boolean = false>(options: Options<DepotApiDepotNameGetData, ThrowOnError>) => { return (options?.client ?? client).get<DepotApiDepotNameGetResponse, DepotApiDepotNameGetError, ThrowOnError>({
    ...options,
    url: '/api/depot/{name}'
}); };

/**
 * Depots
 */
export const depotsApiDepotsGet = <ThrowOnError extends boolean = false>(options?: Options<unknown, ThrowOnError>) => { return (options?.client ?? client).get<DepotsApiDepotsGetResponse, DepotsApiDepotsGetError, ThrowOnError>({
    ...options,
    url: '/api/depots'
}); };