// This file is auto-generated by @hey-api/openapi-ts

export type HTTPValidationError = {
    detail?: Array<ValidationError>;
};

export type ValidationError = {
    loc: Array<(string | number)>;
    msg: string;
    type: string;
};

export type RootApiHelloGetResponse = (unknown);

export type RootApiHelloGetError = unknown;

export type DepotApiDepotNameGetData = {
    path: {
        name: string;
    };
};

export type DepotApiDepotNameGetResponse = (unknown);

export type DepotApiDepotNameGetError = (HTTPValidationError);

export type DepotsApiDepotsGetResponse = (Array<(string)>);

export type DepotsApiDepotsGetError = unknown;